package com.abhishek.smarthome.reports.enums;

/** Why a report exists: the nightly job ({@code DAILY}, one per device per local day) or a user request. */
public enum ReportType {

	/** One per home device per home-local day, generated by the daily report job. */
	DAILY,

	/** Any {@code [from, to)} range, generated on request. */
	CUSTOM_RANGE
}
