package com.abhishek.smarthome.reports.controller;

import com.abhishek.smarthome.reports.dto.input.CreateReportRequest;
import com.abhishek.smarthome.reports.dto.output.ReportResponse;
import com.abhishek.smarthome.reports.enums.ReportType;
import com.abhishek.smarthome.reports.service.ReportService;
import jakarta.validation.Valid;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import org.jspecify.annotations.Nullable;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

/** Device reports: DAILY ones are generated by the daily job, CUSTOM_RANGE ones on request. */
@RestController
@RequestMapping("/api/v1/smart-home")
@RequiredArgsConstructor
class ReportController {

	private final ReportService reportService;

	/** Generates a report over {@code [from, to)} synchronously and returns it. */
	@PostMapping("/home-devices/{homeDeviceId}/reports")
	@ResponseStatus(HttpStatus.CREATED)
	ReportResponse create(@PathVariable UUID homeDeviceId, @Valid @RequestBody CreateReportRequest request) {
		return reportService.createCustomRange(homeDeviceId, request.getFrom(), request.getTo(), request.getMetrics());
	}

	/** Reports of a device starting on home-local days {@code from..to} (ISO dates, inclusive), optionally one type. */
	@GetMapping("/home-devices/{homeDeviceId}/reports")
	List<ReportResponse> list(@PathVariable UUID homeDeviceId,
			@RequestParam(required = false) @Nullable ReportType type,
			@RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate from,
			@RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate to) {
		return reportService.list(homeDeviceId, type, from, to);
	}

	@GetMapping("/reports/{id}")
	ReportResponse get(@PathVariable UUID id) {
		return reportService.get(id);
	}

	/** Recomputes a report from the current readings (e.g. after late data). */
	@PostMapping("/reports/{id}/regenerate")
	ReportResponse regenerate(@PathVariable UUID id) {
		return reportService.regenerate(id);
	}
}
